###############################################################################
#
# META
#

swagger: '2.0'

info:
  version: '0.1.0'
  title: cam0 API

host: 127.0.0.1:4444

basePath: /api

schemes:
  - http

consumes:
  - application/x-www-form-urlencode

produces:
  - application/json


###############################################################################
#
# PATHS
#

paths:

  #######################################
  #
  # ...
  #


###############################################################################
#
# DEFINITIONS
#

definitions:

  #######################################
  #
  # ...
  #
